In [1]:
import numpy as np

In [3]:
a1 = np.array([ [1,2,3], [3,4,5] ])
a2 = np.random.randint(1, 10, size=(3,3))
print(type(a1))
print(id(a1))
print(a1)
a1

<class 'numpy.ndarray'>
2804363633168
[[1 2 3]
 [3 4 5]]


array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
print(a1.shape)
print(a1.ndim)
print(a1.nbytes)
print(a1.dtype)

(2, 3)
2
24
int32


In [10]:
#access elements of 2-d array
print(a2)
print(a2[0,2])
print(a2[:,:])
print(a2[0:2,1:3])
print(a2[[0,2],[1]])

[[1 7 7]
 [1 5 8]
 [5 1 8]]
7
[[1 7 7]
 [1 5 8]
 [5 1 8]]
[[7 7]
 [5 8]]
[7 1]


In [13]:
#create special  2-d arrays
print(np.zeros((2,3), dtype=np.int16))
print(np.ones((2,3), dtype=np.int16))
print(np.eye(3, dtype=np.int16))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
#reshape of 2-d arrays
print(np.reshape(a2, (1,9)))
print(np.reshape(a2, -1))

array([1, 7, 7, 1, 5, 8, 5, 1, 8])

In [24]:
#concatenation
a3 = np.random.randint(1, 10, size=(2,2))
a4 = np.random.randint(1, 10, size=(2,2))
print(a3)
print(a4)
print(np.concatenate([a3, a4]))
print(np.concatenate([a3, a4], axis=1))

[[2 3]
 [4 8]]
[[4 6]
 [5 7]]
[[2 3]
 [4 8]
 [4 6]
 [5 7]]
[[2 3 4 6]
 [4 8 5 7]]


In [23]:
print(np.hstack([a3, a4]))
print(np.vstack([a3, a4]))

[[8 1 1 4]
 [1 8 9 4]]
[[8 1]
 [1 8]
 [1 4]
 [9 4]]
