In [2]:
import numpy as np

In [8]:
def add(mat1, mat2):
    res = np.empty(mat1.shape, dtype=np.int8)
    for i in range(len(mat1)):
        for j in range(len(mat2)):
            res[i,j] = mat1[i,j] + mat2[i,j]
    return res

In [9]:
mat1 = np.random.randint(1, 10, size=(2,2))
print(mat1)
mat2 = np.random.randint(1, 10, size=(2,2))
print(mat2)

[[9 6]
 [2 7]]
[[6 5]
 [4 1]]


In [11]:
%%timeit
add(mat1, mat2)

4.48 µs ± 92 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
mat1+mat2 #np.add(mat1, mat2)

array([[15, 11],
       [ 6,  8]])

In [13]:
%%timeit
mat1+mat2 #np.add(mat1, mat2)

578 ns ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
v = np.array([1,1])
print(v)

[1 1]


In [15]:
mat1 + v

array([[10,  7],
       [ 3,  8]])

In [16]:
np.log(mat1)

array([[2.19722458, 1.79175947],
       [0.69314718, 1.94591015]])

In [17]:
#vectorized arithmetic operations: +, -, *,...
#vectorized log, exp operations: np.log, np.exp,..
#vectorised trigonometric oprations:np.sin, np.cos,...
#vectorized aggregate operations: np.sum, np.min, np.max, np.std, np.mean...
#vectorized relational operations: <, >, <=, >=, ==, !=...

In [21]:
print(mat1)
print(np.min(mat1))
print(np.min(mat1, axis=0))
print(np.min(mat1, axis=1))

[[9 6]
 [2 7]]
2
[2 6]
[6 2]


In [22]:
mat1[mat1<5]

array([2])

In [23]:
mat1<5

array([[False, False],
       [ True, False]])