In [1]:
import numpy as np

In [2]:
#create a random tensor
a1 = np.random.randint(1, 20, size=(2,3,3))
print(type(a1))
print(a1.shape)

<class 'numpy.ndarray'>
(2, 3, 3)


In [7]:
#create a tensor by expansion/reshape
a2 = np.random.randint(1, 10, size=(2,3))
print(a2.shape)
a3 = a2[np.newaxis, :, :]
print(a3.shape)
a4 = a2.reshape((1,2,3))
print(a4.shape)

(2, 3)
(1, 2, 3)
(1, 2, 3)


In [10]:
#create a tensor by reading files
import matplotlib.pyplot as plt
img = plt.imread("C:/users/algorithmica/python/image.jpg")
print(type(img))
print(img.shape)
print(img)

<class 'numpy.ndarray'>
(4000, 6000, 3)
[[[164 182 186]
  [161 179 183]
  [159 177 181]
  ...
  [  9   8   4]
  [  8   7   3]
  [  7   6   2]]

 [[164 182 186]
  [161 179 183]
  [160 178 182]
  ...
  [  9   8   4]
  [  8   7   3]
  [  7   6   2]]

 [[163 183 184]
  [162 180 182]
  [161 179 181]
  ...
  [  9   8   4]
  [  9   8   4]
  [  7   6   2]]

 ...

 [[146 166 167]
  [148 168 169]
  [150 170 171]
  ...
  [  7   6   4]
  [  6   5   3]
  [  7   6   4]]

 [[145 164 168]
  [147 166 170]
  [149 169 170]
  ...
  [  7   6   4]
  [  7   6   4]
  [  7   6   4]]

 [[145 164 168]
  [145 164 168]
  [146 165 169]
  ...
  [  6   5   3]
  [  7   6   4]
  [  7   6   4]]]
