In [1]:
#write a python program to sum all the elements between 20 and 30 in a given array

In [6]:
#loop based approach
import numpy as np
def sum1(inp):
    res = 0
    for x in inp:
        if(x >=20 and x <= 30):
            res += x
    return res

inp1 = np.random.randint(1, 100, size=10)
print(inp1)
sum1(inp1)

[28 48 96 36 18 62 24 77 61 92]


52

In [14]:
inp = np.random.randint(1, 100, size=1000)

In [8]:
%%timeit
sum1(inp)

354 µs ± 9.35 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
#higher order functions approach
from functools import reduce
def sum2(inp):
    return reduce(lambda x,y: x+y, filter(lambda x: x >=20 and x <=30, inp))
inp2 = np.random.randint(1, 100, size=20)
print(inp2)
sum2(inp2)

[61 76 69 18 24 19 50 73 33 79  7 29  7  1 82 51 19  3 98  1]


53

In [15]:
%%timeit
sum2(inp)

473 µs ± 13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
#vectorized approach
def sum3(inp):
   return np.sum(inp[(inp >= 20) & (inp <= 30)])
inp3 = np.random.randint(1, 100, size=10)
print(inp3)
sum3(inp3)

[19 85 71 87 52 45 24 21 57 67]


45

In [20]:
%%timeit
sum3(inp)

11.3 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
