In [1]:
import numpy as np

In [2]:
#create numpy array using np.array
a1 = np.array([10, 20, 30])
print(type(a1))
print(id(a1))
print(a1)
a1

<class 'numpy.ndarray'>
2813414082560
[10 20 30]


array([10, 20, 30])

In [3]:
#attributes of an array
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.nbytes)

(3,)
1
int32
12


In [6]:
a2 = np.array([10, 20, 30], dtype=np.int8)
print(a2)
print(a2.dtype)
print(a2.nbytes)

[10 20 30]
int8
3


In [8]:
#create a numpy array using np.linspace
a3 = np.linspace(0, 1, 4)
print(a3)
a3

[0.         0.33333333 0.66666667 1.        ]


array([0.        , 0.33333333, 0.66666667, 1.        ])

In [13]:
#create a numpy array using np.random.randint
a4 = np.random.randint(1, 10, size=15)
print(a4)
a4

[4 8 4 8 9 9 8 2 2 9 4 3 5 6 6]


array([4, 8, 4, 8, 9, 9, 8, 2, 2, 9, 4, 3, 5, 6, 6])

In [17]:
#create special 1-d arrays
print(np.zeros(3, dtype=np.int8))
print(np.ones(3, dtype=np.int8))
print(np.empty(3))

[0 0 0]
[1 1 1]
[0. 0. 0.]


In [22]:
#access elements of 1-d array
a5 = np.array([1, 5, 6, 8, 9, 10])
print(a5[2])
print(a5[3:6])
print(a5[1:4:2])
print(a5[-1])
print(a5[[0,2]]) #fancy indexing

6
[ 8  9 10]
[5 8]
10
[1 6]


In [24]:
#clone/copy of 1-d array
a6 = a5
print(id(a6))
print(id(a5))
a7 = a5.copy()
print(id(a7))

2813414234912
2813414234912
2813414252912


In [34]:
#reshape
print(a5.shape)
print(a5.reshape(2,3))
print(a5.reshape(1,6))
print(a5[np.newaxis, :])
print(a5.reshape(6,1))
print(a5[:, np.newaxis])

(6,)
[[ 1  5  6]
 [ 8  9 10]]
[[ 1  5  6  8  9 10]]
[[ 1  5  6  8  9 10]]
[[ 1]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]]
[[ 1]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]]
