In [1]:
#write a python program to substract mean of array from each element of the array

In [2]:
import numpy as np

def substractMean(arr, c):
    for i in range(len(arr)):
        arr[i] = arr[i] - c

In [7]:
arr = np.arange(1, 10)
print(arr)
arr
m = np.mean(arr)
print(m)
substractMean(arr, m)
print(arr)

[1 2 3 4 5 6 7 8 9]
5.0
[-4 -3 -2 -1  0  1  2  3  4]


In [8]:
%%timeit
substractMean(arr, m)

26.8 µs ± 486 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
arr = np.arange(1, 10)
print(arr - m)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]


In [11]:
%%timeit
arr-m

1.98 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%%timeit
np.subtract(arr, m)

1.92 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
#arithmatic operations: +, -, *, /, //, np.add, np.subtract, np.div.,,,
#log, exp, abs operations: np.log, np.exp, np.abs,...
#trigonometric operations:np.sin, np.cos,...

In [14]:
a = np.arange(1, 100)
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748

In [15]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21, 5.18470553e+21, 1.40934908e+22, 3.83100800e+22,
       1.04137594e+23, 2.83075330e+23, 7.69478527e+23, 2.09165950e+24,
      

In [16]:
np.abs(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])