In [1]:
#write a python program to display all the temperatures in a given array > 40

In [2]:
import numpy as np

In [5]:
def getTemp(arr):
    res = []
    for i in range(len(arr)):
        if(arr[i] > 40):
           res.append(arr[i])
    return np.array(res)

In [6]:
arr = np.random.randint(1,50, 100)
print(arr)
print(getTemp(arr))

[33  2 39  7 47 10 28 14 20 21 41 16 18 18  5  8 44 45 27  2 25 15  3  8
 33 35 35 16  5 41 43 38 43 18 27 19 11 18 38 49 36 16 29 23 15 30 29 17
 30 48 47 39 16 37 29 18 41  9 39 39 22  6 31 21 11  3 17  9 25 41 22 23
 15  1 44 33  9 18 13  5 41 11 19  2 43 21 17 48 30 12 11  5 38 39 38 36
 23 20  4 29]
[47 41 44 45 41 43 43 49 48 47 41 41 44 41 43 48]


In [7]:
%%timeit
getTemp(arr)

35.1 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
a = np.arange(1, 10)
print(a > 5)
#access elements by mask
print(a[a>5])
#access elements by index
print(a[0:3])
#access element by fancy index
print(a[[0,5,6]])

[False False False False False  True  True  True  True]
[6 7 8 9]
[1 2 3]
[1 6 7]


In [13]:
arr[arr>40]

array([47, 41, 44, 45, 41, 43, 43, 49, 48, 47, 41, 41, 44, 41, 43, 48])

In [14]:
%%timeit
arr[arr>40]

1.68 µs ± 21.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
#vectorized logical operations: >, <, ==, !=, <=, >=, np.greater, np.less, np.equal.....